#!/bin/sh

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 SOURCE_DISK DESTINATION_PATH"
    exit 1
fi

src_disk=$1
dst_path=$2

if [ ! -b "$src_disk" ]; then
    echo "Source disk doesn't exist"
    exit 1
fi

if [ ! -d "$dst_path" ]; then
    echo "Destination path is invalid"
    exit 1
fi

filename="$dst_path/backup.img"

# Make the image
if ! dd if="$src_disk" of="$filename" bs=4M conv=sync,noerror status=progress; then
    echo "There was an error while creating the image"
    exit 1
fi

# Compress the image
if ! gzip "$filename"; then
    echo "There was an error while compressing the image (no permission?)"
    exit 1
fi

echo "Done."
echo "Image path: $filename.gz"
