#!/bin/sh

date=$(date)
user=$(whoami)
systeminfo=$(uname -a)
path=$PATH
vars=$(env)

rm systeminfo.txt

{
    echo "Date:"
    echo "----"
    echo "$date"
    echo ""
    echo "User:"
    echo "----"
    echo "$user"
    echo ""
    echo "System info:"
    echo "-----------"
    echo "$systeminfo"
    echo ""
    echo "Path:"
    echo "----"
    echo "$path"
    echo ""
    echo "Environment variables:"
    echo "---------------------"
    echo "$vars"
} >>systeminfo.txt
